version: '3.7'
services:
  angular-service:
    container_name: student-survey-frontend
    build: .
    networks:
      - backend
    ports:
      - '4200:80'
     
  backend-service:
    container_name: student-survey-backend
    build: ./backend/surveyform/
    networks:
      - backend
    ports:
      - '9090:9090'

networks:
  backend:
    driver: bridge